version: '3.8'

services:
  redis-master:
    container_name: redis-master
    image: redis:7.2
    restart: always
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./master/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_master_data:/data
    ports:
      - "6379:6379"
    networks:
      - redis_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-slave:
    container_name: redis-slave
    image: redis:7.2
    restart: always
    depends_on:
      redis-master:
        condition: service_healthy
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./slave/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_slave_data:/data
    ports:
      - "6380:6379"
    networks:
      - redis_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_master_data:
  redis_slave_data:

networks:
  redis_net:
    driver: bridge
